# Setting up a conda environment for pygrnd

name: pygrnd
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib
  - python
  - pip
  - pip:
    - qiskit
    - scipy
    - jupyter
    - dimod
    - dwave-greedy
    
