name: pygrnd
dependencies:
  - pip
  - pip:
    - qiskitqiskit>=0.32.1
    - numpy
    - scipy
    - jupyter
    - matplotlib
    - pylatexenc
    - networkx
    - dimod
    - dwave-greedy
    - dwave-neal
    - pennylane>=0.27.0
    - pandas
    - tqdm
    - scikit-learn
    - DateTime
    - shap
    - xgboost
    - holidays
    - imblearn
