name: pygrnd
dependencies:
  - numpy
  - scipy
  - jupyter
  - matplotlib
  - pylatexenc
  - networkx
  - pip
  - pip:
    - qiskit
    - dimod
    - dwave-greedy
    - dwave-neal
    - pennylane
    - pandas
    - tqdm
    - scikit-learn
